version: "3.9"

services:
  app:
    build: .
    container_name: express_app
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      DB_NAME: ets-db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
    volumes:
    - .:/usr/src/app
    # - node_modules:/usr/src/app/node_modules
    command: npx nodemon --legacy-watch index.js

  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: ets-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
  node_modules:
